# Manage nginx htpasswd files stored in /etc/nginx/htpasswd
#
# Expects:
#
#   * name: Filename to use
#   * users: A data structure containing the users to be managed. It should
#            be structured like so:
#
#            users:
#              - username: foo
#                password: secret
#                state: present  # Optional
#              - username: bar
#                password: secret
#                state: absent
#
# Warning:
#
#   This file may be symlinked to by other roles
---
- name: Manage htpasswd users
  htpasswd:
    path: /etc/nginx/htpasswd/{{ name }}
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: "{{ item.state|default('present') }}"
  with_items: users
  tags: [config,configuration]

- name: Manage htpasswd file permissions
  file:
    path: /etc/nginx/htpasswd/{{ name }}
    owner: root
    group: www-data
    mode: 0640
