---

- include: ../../../snippets/require-debian-family.yml

- include: system.yml

- name: Determine if wordpress is installed
  command: "test -e {{ wordpress_dir }}/wordpress"
  register: wordpress_installed
  changed_when: false
  failed_when: false

- include: install-wordpress.yml
  when: wordpress_installed.rc != 0

- include: webserver.yml

- include: mysql.yml
