---

- name: Install defaults file
  template:
    src: varnish.default
    dest: /etc/default/varnish
    owner: root
    group: root
    mode: "644"
  notify:
     - Reload varnish
  tags: [config,varnish]

- name: Install vcl file
  template:
    src: varnish.vcl
    dest: /etc/varnish/default.vcl
    owner: root
    group: root
    mode: "644"
    validate: varnishd -C -f %s
  notify:
     - Reload varnish
  tags: [config,varnish]

- name: Make sure varnish is started and running at boot
  service:
    name: varnish
    state: started
  tags: [varnish,service]
