---

- include: ../../../snippets/require-debian-family.yml

- name: Install dependencies
  apt:
    name: phpmyadmin
    state: present
  register: phpmyadmin_installed
  tags: [apt,packages,dependencies]

- include: setup.yml
  when: phpmyadmin_installed.changed

- name: Create user
  user:
    state: present
    name: phpmyadmin
    shell: /bin/false
    home: /usr/share/phpmyadmin
    createhome: no
  tags: [user]

- name: Create fpm pool
  template:
    src: fpm-pool.j2
    dest: /etc/php5/fpm/pool.d/phpmyadmin.conf
    owner: root
    group: root
    mode: "644"
  notify:
    - Restart fpm
  tags: [fpm,php]

- include: install-site.yml
  name: phpmyadmin
  src: nginx.j2
