---

- include: ../../nginx/handlers/main.yml
- include: ../../php/fpm/handlers/main.yml

- name: Reload varnish
  service:
    name: varnish
    state: reloaded

- name: Restart varnish
  service:
    name: varnish
    state: restarted
